import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const OUT = process.env.SHOTS; mkdirSync(OUT, { recursive: true });
const UI = 'http://localhost:5173';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 900 } });
const run = async (lot) => {
  await p.goto(`${UI}/incoming`, { waitUntil: 'networkidle' });
  await p.waitForTimeout(2000);
  const btn = p.locator(`[data-evaluate-lot="${lot}"]`);
  await btn.waitFor({ timeout: 20000 }); await btn.click();
  await p.waitForTimeout(38000);
};
await p.goto(`${UI}/today`, { waitUntil: 'networkidle' });
await p.waitForTimeout(2000);
await p.screenshot({ path: `${OUT}/A-today-opening.png` });
console.log('A captured');
await run('LOT-1001');
await p.goto(`${UI}/today`, { waitUntil: 'networkidle' });
await p.waitForTimeout(2500);
await p.screenshot({ path: `${OUT}/B-today-after-1001.png` });
console.log('B captured');
await run('LOT-1002');
await p.goto(`${UI}/today`, { waitUntil: 'networkidle' });
await p.waitForTimeout(2500);
await p.screenshot({ path: `${OUT}/C-today-after-1002.png` });
console.log('C captured');
await b.close();
